addEventListener("fetch", event => event.respondWith(handle(event.request)));

function basePage(title, body, extra='') {
  return `<!doctype html><html><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>${title}</title><style>body{font-family:Inter,Arial,sans-serif;margin:0;background:#0b1220;color:#fff}.wrap{max-width:980px;margin:0 auto;padding:30px 18px}.top{display:flex;justify-content:space-between;align-items:center;gap:10px}.brand{font-weight:800;font-size:24px}.muted{color:#94a3b8}.card{background:#111827;border:1px solid #1f2937;border-radius:12px;padding:16px}.btn{display:inline-block;padding:10px 14px;border-radius:10px;border:1px solid #334155;background:#ffffff08;color:#fff;text-decoration:none;cursor:pointer}.btn-primary{background:#2563eb;border-color:#2563eb}.row{display:flex;gap:10px;flex-wrap:wrap}.in{width:100%;padding:10px;border-radius:10px;border:1px solid #334155;background:#0f172a;color:#fff;margin:8px 0}.tabs{display:flex;gap:8px;margin-bottom:14px}.tab{padding:8px 12px;border:1px solid #334155;border-radius:10px;color:#fff;text-decoration:none}.tab.active{background:#2563eb;border-color:#2563eb}</style>${extra}</head><body><div class="wrap">${body}</div></body></html>`;
}

function landingPage(){
  return basePage('Real Connections, Curated by AI | Bligo', `<div class="top"><div class="brand">Bligo</div><div class="row"><a class="btn btn-primary" href="/signin">Sign In</a><a class="btn" href="#waitlist">Join Waitlist</a></div></div><section style="margin-top:42px"><div class="muted" style="letter-spacing:.12em;font-size:12px">MEET BLIGO</div><h1 style="font-size:46px;line-height:1.05;margin:8px 0 10px">Real connections, curated by AI.</h1><p class="muted" style="font-size:18px">Your own smarter network.</p><p class="muted" style="max-width:860px;line-height:1.6">Bligo helps you unlock new connections across your personal network. Share your intent, and AI surfaces high-fit matches within your direct and extended circles. You approve the introduction, they accept, and a private conversation opens.</p><div class="row" style="margin-top:14px"><a class="btn btn-primary" href="/signin">Connect Your Personal AI</a><a class="btn" href="/signin">Sign In</a></div></section><section id="waitlist" style="margin-top:42px;max-width:560px"><h3>Join Waitlist</h3><input class="in" placeholder="Email*"/><input class="in" placeholder="Role / Specialty"/><input class="in" placeholder="What should AI help you find?"/><button class="btn btn-primary">Save my spot</button></section>`);
}

function signinPage(){
  return basePage('Sign In | Bligo', `<div class="top"><div class="brand">Bligo</div><a class="btn" href="/">Back</a></div><section style="max-width:480px;margin:42px auto 0" class="card"><div class="tabs"><a class="tab active" href="/signin">Sign In</a><a class="tab" href="/signup">Sign Up</a></div><h2 style="margin-top:0">Sign in to Bligo</h2><form id="f"><input id="e" class="in" type="email" placeholder="Email" required/><input id="p" class="in" type="password" placeholder="Password" required/><button class="btn btn-primary" type="submit">Sign In</button></form><p id="err" style="display:none;color:#fca5a5">Invalid email or password.</p></section>`, `<script>document.getElementById('f').addEventListener('submit',ev=>{ev.preventDefault();const e=document.getElementById('e').value.trim();const p=document.getElementById('p').value;const ok=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)&&p.length>=6;if(!ok){document.getElementById('err').style.display='block';return;}localStorage.setItem('bligo_auth',JSON.stringify({email:e,at:Date.now()}));location.href='/app';});<\/script>`);
}

function signupPage(){
  return basePage('Sign Up | Bligo', `<div class="top"><div class="brand">Bligo</div><a class="btn" href="/">Back</a></div><section style="max-width:520px;margin:42px auto 0" class="card"><div class="tabs"><a class="tab" href="/signin">Sign In</a><a class="tab active" href="/signup">Sign Up</a></div><h2 style="margin-top:0">Create your account</h2><form id="s"><input id="n" class="in" placeholder="Full name" required/><input id="e" class="in" type="email" placeholder="Email" required/><input id="p" class="in" type="password" placeholder="Password (min 6)" required/><button class="btn btn-primary" type="submit">Create Account</button></form><p id="msg" style="display:none;color:#86efac">Account created. Redirecting…</p></section>`, `<script>document.getElementById('s').addEventListener('submit',ev=>{ev.preventDefault();const n=document.getElementById('n').value.trim();const e=document.getElementById('e').value.trim();const p=document.getElementById('p').value;const ok=n.length>1&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)&&p.length>=6;if(!ok)return;localStorage.setItem('bligo_user',JSON.stringify({name:n,email:e}));localStorage.setItem('bligo_auth',JSON.stringify({email:e,at:Date.now()}));document.getElementById('msg').style.display='block';setTimeout(()=>location.href='/app',600);});<\/script>`);
}

function appPage(){
  return basePage('Bligo — Signed In', `<div class="top"><div class="brand">Bligo</div><div class="row"><a class="btn" href="/">Landing</a><button id="out" class="btn">Sign Out</button></div></div><section class="card" style="margin-top:22px"><h2 style="margin-top:0">Welcome to your Bligo feed</h2><p id="who" class="muted"></p><div class="card" style="margin-top:10px"><b>Ava Bennett</b><p class="muted">We reduced labor by redesigning shifts.</p></div><div class="card" style="margin-top:10px"><b>Marco Ruiz</b><p class="muted">Opportunity: growth partner needed.</p></div></section>`, `<script>const a=JSON.parse(localStorage.getItem('bligo_auth')||'null');if(!a){location.href='/signin';}else{document.getElementById('who').textContent='Signed in as: '+a.email;}document.getElementById('out').onclick=()=>{localStorage.removeItem('bligo_auth');location.href='/';};<\/script>`);
}

async function handle(request){
  const path = new URL(request.url).pathname;
  const html = (path==='/signin'||path==='/signin/') ? signinPage() : (path==='/signup'||path==='/signup/') ? signupPage() : (path==='/app'||path==='/app/') ? appPage() : landingPage();
  return new Response(html,{headers:{'content-type':'text/html; charset=UTF-8','cache-control':'no-store'}});
}
